config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#home'
  get '/home', to: 'static#home'
  get '/index', to: redirect('/')
  get '/shop', to: 'static#shop', as: 'shop'
  get '/contact', to: 'static#contact'
  get '/product_details/:id', to: 'static#product_details', as: 'product_details'
  post '/add_to_cart', to: 'static#add_to_cart', as: 'add_to_cart'
  get '/cart', to: 'static#cart', as: 'cart'
  get '/order_confirmation/:id', to: 'static#order_confirmation', as: 'order_confirmation'

  scope '/admin' do
    root to: "products#index"
    resources :products
    resources :orders, only: [:index, :show, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product

  def spend
    product.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :items, class_name: "OrderItem", dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def spend
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  ADMIN_USER = 'admin'
  ADMIN_PASS = 'admin'
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  layout 'admin'
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with :name => ADMIN_USER, :password => ADMIN_PASS, except: :create

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(total: 0)
    CartItem.transaction do
      @order.save!
      CartItem.all.each do |item|
        @order.items.create!(
          product_id: item.product_id,
          quantity: item.quantity
        )
        @order.total += item.spend
      end
      @order.save!
      CartItem.delete_all
    end

    redirect_to order_confirmation_url(@order.id)
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:total)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  layout 'admin'
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  http_basic_authenticate_with :name => ADMIN_USER, :password => ADMIN_PASS

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).
        permit(:name, :category, :short_desc, :full_desc, :price, :stocked, :image)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  # def home
  # end

  # def contact
  # end

  def shop
    @products = Product.all
  end

  def product_details
    @product = Product.find(params[:id])
  end

  def add_to_cart
    id = params[:id]
    qty = params[:quantity] || 1
    ci = CartItem.where(product_id: id).first
    if ci
      ci.quantity += 1
    else
      ci = CartItem.new(product_id: id, quantity: qty)
    end
    ci.save!

    render json: {status: '200', message: "OK"}
  end

  def cart
    @items = CartItem.includes(:product).all.to_a
    @total = @items.map {|item| item.product.price * item.quantity }.sum
  end

  def order_confirmation
    @order = Order.includes(:items).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_price(price)
    "$%0.2f" % [price]
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin View</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" href="img/Fevicon.png" type="image/png">

    <%= stylesheet_link_tag    'admin', media: 'all' %>
    <%= javascript_include_tag 'admin' %>
  </head>

  <body>
    <p>Menu:
      <%= link_to "Products", products_path %> |
      <%= link_to "Orders", orders_path %>
    </p>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aroma Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" href="/img/Fevicon.png" type="image/png">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <!--================ Start Header Menu Area =================-->
    <header class="header_area">
      <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container">
            <a class="navbar-brand logo_h" href="/index.html"><img src="/img/logo.png" alt=""></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
              <ul class="nav navbar-nav menu_nav ml-auto mr-auto">
                <li class="nav-item"><a class="nav-link" href="/index.html">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="/shop.html">Shop</a></li>
                <li class="nav-item"><a class="nav-link" href="/contact.html">Contact</a></li>
              </ul>

              <ul class="nav-shop">
                <li class="nav-item"><button><i class="ti-search"></i></button></li>
                <li class="nav-item">
                  <%= link_to cart_path do %>
                  <button>
                    <i class="ti-shopping-cart"></i>
                    <span class="nav-shop__circle">3</span>
                  </button>
                  <% end  %>
                </li>
                <li class="nav-item">
                  <%= link_to cart_path, class: "button button-header" do %>
                    Buy Now
                  <% end  %>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </header>
    <!--================ End Header Menu Area =================-->

    <%= yield %>

    <!--================ Start footer Area  =================-->
    <footer class="footer">
      <div class="footer-area">
        <div class="container">
          <div class="row section_gap">
            <div class="col-lg-3 col-md-6 col-sm-6">
              <div class="single-footer-widget tp_widgets">
                <h4 class="footer_title large_title">Our Mission</h4>
                <p>
                  So seed seed green that winged cattle in. Gathering thing made fly you're no
                  divided deep moved us lan Gathering thing us land years living.
                </p>
                <p>
                  So seed seed green that winged cattle in. Gathering thing made fly you're no divided deep moved
                </p>
              </div>
            </div>
            <div class="offset-lg-1 col-lg-2 col-md-6 col-sm-6">
              <div class="single-footer-widget tp_widgets">
                <h4 class="footer_title">Quick Links</h4>
                <ul class="list">
                  <li><a href="#">Home</a></li>
                  <li><a href="#">Shop</a></li>
                  <li><a href="#">Blog</a></li>
                  <li><a href="#">Product</a></li>
                  <li><a href="#">Brand</a></li>
                  <li><a href="#">Contact</a></li>
                </ul>
              </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
              <div class="single-footer-widget instafeed">
                <h4 class="footer_title">Gallery</h4>
                <ul class="list instafeed d-flex flex-wrap">
                  <li><img src="/img/gallery/r1.jpg" alt=""></li>
                  <li><img src="/img/gallery/r2.jpg" alt=""></li>
                  <li><img src="/img/gallery/r3.jpg" alt=""></li>
                  <li><img src="/img/gallery/r5.jpg" alt=""></li>
                  <li><img src="/img/gallery/r7.jpg" alt=""></li>
                  <li><img src="/img/gallery/r8.jpg" alt=""></li>
                </ul>
              </div>
            </div>
            <div class="offset-lg-1 col-lg-3 col-md-6 col-sm-6">
              <div class="single-footer-widget tp_widgets">
                <h4 class="footer_title">Contact Us</h4>
                <div class="ml-40">
                  <p class="sm-head">
                    <span class="fa fa-location-arrow"></span>
                    Head Office
                  </p>
                  <p>123, Main Street, Your City</p>

                  <p class="sm-head">
                    <span class="fa fa-phone"></span>
                    Phone Number
                  </p>
                  <p>
                    +123 456 7890 <br>
                    +123 456 7890
                  </p>

                  <p class="sm-head">
                    <span class="fa fa-envelope"></span>
                    Email
                  </p>
                  <p>
                    free@infoexample.com <br>
                    www.infoexample.com
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="footer-bottom">
        <div class="container">
          <div class="row d-flex">
            <p class="col-lg-12 footer-text text-center">
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>
    <!--================ End footer Area  =================-->
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Item Count</th>
      <th>Total Spend</th>
      <th>Date</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.items.count %></td>
        <td><%= format_price(order.total) %></td>
        <td><%= order.created_at.to_s %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @order.id %>
</p>

<p>
  <strong>Total:</strong>
  <%= format_price(@order.total) %>
</p>

<p>
  <strong>Date:</strong>
  <%= @order.created_at %>
</p>

<p>
  <strong>Items:</strong>
  <ul>
  <% @order.items.each do |item| %>
    <li>
      <%= item.product.name %> (Qty: <%= item.quantity %>)
    </li>
  <% end  %>
  </ul>
</p>

<%= link_to 'Back', orders_path %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :short_desc %>
    <%= form.text_area :short_desc %>
  </div>

  <div class="field">
    <%= form.label :full_desc %>
    <%= form.text_field :full_desc %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :stocked %>
    <%= form.check_box :stocked %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Category</th>
      <th>Short desc</th>
      <th>Full desc</th>
      <th>Price</th>
      <th>Stocked</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= image_tag product.image.variant(resize: "100x100") %></td>
        <td><%= product.category %></td>
        <td><%= product.short_desc %></td>
        <td><%= product.full_desc %></td>
        <td><%= product.price %></td>
        <td><%= product.stocked %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image</strong>
  <%= image_tag @product.image.variant(resize: "100x100") %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Short desc:</strong>
  <%= @product.short_desc %>
</p>

<p>
  <strong>Full desc:</strong>
  <%= @product.full_desc %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Stocked:</strong>
  <%= @product.stocked %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>